name: "dbt_scooters"
version: "1.0.0"
config-version: 2
profile: "default"
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
vars:
  "dbt_date:time_zone": "Europe/Moscow"
on-run-end:
    - "grant usage on schema finance to finance;"
models:
  dbt_scooters:
    +materialized: "table"
    +on_schema_change: "append_new_columns"
    +persist_docs:
      relation: true
      columns: true
    finance:
      +schema: "finance"
seeds:
  dbt_scooters:
    +persist_docs:
      relation: true
      columns: true
