default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dpg-cnrfh4ect0pc73crsupg-a.frankfurt-postgres.render.com
      port: 5432
      user: admin
      dbname: dev_z5w0
      password: {{ env_var('DBT_ENV_SECRET_PASSWORD') }}
      schema: dbt
      threads: 4
