[project]
name = "dbt-scooters"
version = "0.1.0"
description = "dbt project to prepare and analyze scooter data"
requires-python = ">=3.9,<3.13"
dependencies = [
    "dbt-core==1.10.11",
    "dbt-metricflow==0.10.1",
    "dbt-postgres==1.9.1",
]
